package ee.cone.c4actor.rdb_impl

import ee.cone.c4actor.rdb.ExternalActivatorApp

trait IndentedParserAppBase
trait RDBSyncAppBase extends ExternalActivatorApp with IndentedParserApp
trait ToExternalDBSyncAppBase extends RDBSyncApp
trait FromExternalDBSyncAppBase extends RDBSyncApp