services:
  node:
    command: ["sh","-c","cp src/vite/* . && npm install && npm run dev"]
    image: node:14.3.0
    volumes:
    - ../../src:/app/src
#    - ../../build:/app/build
    working_dir: /app
    ports:
    - "127.0.0.10:3000:3000"
  haproxy:
    image: haproxy:1.7
    volumes:
    - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
    - "127.0.0.10:80:1080"
version: '2'
